<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>W3.CSS Template</title>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<style>';
echo 'body {font-family: "Lato", sans-serif}';
echo '.mySlides {display: none}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<!-- Navbar -->';
echo '<div class="w3-top">';
echo '<div class="w3-bar w3-black w3-card">';
echo '<a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>';
echo '<a href="#" class="w3-bar-item w3-button w3-padding-large">HOME</a>';
echo '<a href="#band" class="w3-bar-item w3-button w3-padding-large w3-hide-small">BAND</a>';
echo '<a href="#tour" class="w3-bar-item w3-button w3-padding-large w3-hide-small">TOUR</a>';
echo '<a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hide-small">CONTACT</a>';
echo '<div class="w3-dropdown-hover w3-hide-small">';
echo '<button class="w3-padding-large w3-button" title="More">MORE <i class="fa fa-caret-down"></i></button>';
echo '<div class="w3-dropdown-content w3-bar-block w3-card-4">';
echo '<a href="#" class="w3-bar-item w3-button">Merchandise</a>';
echo '<a href="#" class="w3-bar-item w3-button">Extras</a>';
echo '<a href="#" class="w3-bar-item w3-button">Media</a>';
echo '</div>';
echo '</div>';
echo '<a href="javascript:void(0)" class="w3-padding-large w3-hover-red w3-hide-small w3-right"><i class="fa fa-search"></i></a>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->';
echo '<div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">';
echo '<a href="#band" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">BAND</a>';
echo '<a href="#tour" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">TOUR</a>';
echo '<a href="#contact" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CONTACT</a>';
echo '<a href="#" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">MERCH</a>';
echo '</div>';
echo '';
echo '<!-- Page content -->';
echo '<div class="w3-content" style="max-width:2000px;margin-top:46px">';
echo '';
echo '<!-- Automatic Slideshow Images -->';
echo '<div class="mySlides w3-display-container w3-center">';
echo '<img src="/w3images/la.jpg" style="width:100%">';
echo '<div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">';
echo '<h3>Los Angeles</h3>';
echo '<p><b>We had the best time playing at Venice Beach!</b></p>';
echo '</div>';
echo '</div>';
echo '<div class="mySlides w3-display-container w3-center">';
echo '<img src="/w3images/ny.jpg" style="width:100%">';
echo '<div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">';
echo '<h3>New York</h3>';
echo '<p><b>The atmosphere in New York is lorem ipsum.</b></p>';
echo '</div>';
echo '</div>';
echo '<div class="mySlides w3-display-container w3-center">';
echo '<img src="/w3images/chicago.jpg" style="width:100%">';
echo '<div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">';
echo '<h3>Chicago</h3>';
echo '<p><b>Thank you, Chicago - A night we won't forget.</b></p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- The Band Section -->';
echo '<div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="band">';
echo '<h2 class="w3-wide">Dilvir Singh</h2>';
echo '<p class="w3-opacity"><i>Team Lead Alphanet</i></p>';
echo '<p class="w3-justify">We have created a fictional band website. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip';
echo 'ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur';
echo 'adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>';
echo '<div class="w3-row w3-padding-32">';
echo '<div class="w3-third">';
echo '<p>Name</p>';
echo '<img src="/w3images/bandmember.jpg" class="w3-round w3-margin-bottom" alt="Random Name" style="width:60%">';
echo '</div>';
echo '<div class="w3-third">';
echo '<p>Name</p>';
echo '<img src="/w3images/bandmember.jpg" class="w3-round w3-margin-bottom" alt="Random Name" style="width:60%">';
echo '</div>';
echo '<div class="w3-third">';
echo '<p>Name</p>';
echo '<img src="/w3images/bandmember.jpg" class="w3-round" alt="Random Name" style="width:60%">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- The Tour Section -->';
echo '<div class="w3-black" id="tour">';
echo '<div class="w3-container w3-content w3-padding-64" style="max-width:800px">';
echo '<h2 class="w3-wide w3-center">TOUR DATES</h2>';
echo '<p class="w3-opacity w3-center"><i>Remember to book your tickets!</i></p><br>';
echo '';
echo '<ul class="w3-ul w3-border w3-white w3-text-grey">';
echo '<li class="w3-padding">September <span class="w3-tag w3-red w3-margin-left">Sold out</span></li>';
echo '<li class="w3-padding">October <span class="w3-tag w3-red w3-margin-left">Sold out</span></li>';
echo '<li class="w3-padding">November <span class="w3-badge w3-right w3-margin-right">3</span></li>';
echo '</ul>';
echo '';
echo '<div class="w3-row-padding w3-padding-32" style="margin:0 -16px">';
echo '<div class="w3-third w3-margin-bottom">';
echo '<img src="/w3images/newyork.jpg" alt="New York" style="width:100%" class="w3-hover-opacity">';
echo '<div class="w3-container w3-white">';
echo '<p><b>New York</b></p>';
echo '<p class="w3-opacity">Fri 27 Nov 2016</p>';
echo '<p>Praesent tincidunt sed tellus ut rutrum sed vitae justo.</p>';
echo '<button class="w3-button w3-black w3-margin-bottom" onclick="document.getElementById('ticketModal').style.display='block'">Buy Tickets</button>';
echo '</div>';
echo '</div>';
echo '<div class="w3-third w3-margin-bottom">';
echo '<img src="/w3images/paris.jpg" alt="Paris" style="width:100%" class="w3-hover-opacity">';
echo '<div class="w3-container w3-white">';
echo '<p><b>Paris</b></p>';
echo '<p class="w3-opacity">Sat 28 Nov 2016</p>';
echo '<p>Praesent tincidunt sed tellus ut rutrum sed vitae justo.</p>';
echo '<button class="w3-button w3-black w3-margin-bottom" onclick="document.getElementById('ticketModal').style.display='block'">Buy Tickets</button>';
echo '</div>';
echo '</div>';
echo '<div class="w3-third w3-margin-bottom">';
echo '<img src="/w3images/sanfran.jpg" alt="San Francisco" style="width:100%" class="w3-hover-opacity">';
echo '<div class="w3-container w3-white">';
echo '<p><b>San Francisco</b></p>';
echo '<p class="w3-opacity">Sun 29 Nov 2016</p>';
echo '<p>Praesent tincidunt sed tellus ut rutrum sed vitae justo.</p>';
echo '<button class="w3-button w3-black w3-margin-bottom" onclick="document.getElementById('ticketModal').style.display='block'">Buy Tickets</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Ticket Modal -->';
echo '<div id="ticketModal" class="w3-modal">';
echo '<div class="w3-modal-content w3-animate-top w3-card-4">';
echo '<header class="w3-container w3-teal w3-center w3-padding-32">';
echo '<span onclick="document.getElementById('ticketModal').style.display='none'"';
echo 'class="w3-button w3-teal w3-xlarge w3-display-topright">×</span>';
echo '<h2 class="w3-wide"><i class="fa fa-suitcase w3-margin-right"></i>Tickets</h2>';
echo '</header>';
echo '<div class="w3-container">';
echo '<p><label><i class="fa fa-shopping-cart"></i> Tickets, $15 per person</label></p>';
echo '<input class="w3-input w3-border" type="text" placeholder="How many?">';
echo '<p><label><i class="fa fa-user"></i> Send To</label></p>';
echo '<input class="w3-input w3-border" type="text" placeholder="Enter email">';
echo '<button class="w3-button w3-block w3-teal w3-padding-16 w3-section w3-right">PAY <i class="fa fa-check"></i></button>';
echo '<button class="w3-button w3-red w3-section" onclick="document.getElementById('ticketModal').style.display='none'">Close <i class="fa fa-remove"></i></button>';
echo '<p class="w3-right">Need <a href="#" class="w3-text-blue">help?</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- The Contact Section -->';
echo '<div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="contact">';
echo '<h2 class="w3-wide w3-center">CONTACT</h2>';
echo '<p class="w3-opacity w3-center"><i>Fan? Drop a note!</i></p>';
echo '<div class="w3-row w3-padding-32">';
echo '<div class="w3-col m6 w3-large w3-margin-bottom">';
echo '<i class="fa fa-map-marker" style="width:30px"></i> Chicago, US<br>';
echo '<i class="fa fa-phone" style="width:30px"></i> Phone: +00 151515<br>';
echo '<i class="fa fa-envelope" style="width:30px"> </i> Email: mail@mail.com<br>';
echo '</div>';
echo '<div class="w3-col m6">';
echo '<form action="/action_page.php" target="_blank">';
echo '<div class="w3-row-padding" style="margin:0 -16px 8px -16px">';
echo '<div class="w3-half">';
echo '<input class="w3-input w3-border" type="text" placeholder="Name" required name="Name">';
echo '</div>';
echo '<div class="w3-half">';
echo '<input class="w3-input w3-border" type="text" placeholder="Email" required name="Email">';
echo '</div>';
echo '</div>';
echo '<input class="w3-input w3-border" type="text" placeholder="Message" required name="Message">';
echo '<button class="w3-button w3-black w3-section w3-right" type="submit">SEND</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- End Page Content -->';
echo '</div>';
echo '';
echo '<!-- Image of location/map -->';
echo '<img src="/w3images/map.jpg" class="w3-image w3-greyscale-min" style="width:100%">';
echo '';
echo '<!-- Footer -->';
echo '<footer class="w3-container w3-padding-64 w3-center w3-opacity w3-light-grey w3-xlarge">';
echo '<i class="fa fa-facebook-official w3-hover-opacity"></i>';
echo '<i class="fa fa-instagram w3-hover-opacity"></i>';
echo '<i class="fa fa-snapchat w3-hover-opacity"></i>';
echo '<i class="fa fa-pinterest-p w3-hover-opacity"></i>';
echo '<i class="fa fa-twitter w3-hover-opacity"></i>';
echo '<i class="fa fa-linkedin w3-hover-opacity"></i>';
echo '<p class="w3-medium">Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>';
echo '</footer>';
echo '';
echo '<script>';
echo '// Automatic Slideshow - change image every 4 seconds';
echo 'var myIndex = 0;';
echo 'carousel();';
echo '';
echo 'function carousel() {';
echo 'var i;';
echo 'var x = document.getElementsByClassName("mySlides");';
echo 'for (i = 0; i < x.length; i++) {';
echo 'x[i].style.display = "none";';
echo '}';
echo 'myIndex++;';
echo 'if (myIndex > x.length) {myIndex = 1}';
echo 'x[myIndex-1].style.display = "block";';
echo 'setTimeout(carousel, 4000);';
echo '}';
echo '';
echo '// Used to toggle the menu on small screens when clicking on the menu button';
echo 'function myFunction() {';
echo 'var x = document.getElementById("navDemo");';
echo 'if (x.className.indexOf("w3-show") == -1) {';
echo 'x.className += " w3-show";';
echo '} else {';
echo 'x.className = x.className.replace(" w3-show", "");';
echo '}';
echo '}';
echo '';
echo '// When the user clicks anywhere outside of the modal, close it';
echo 'var modal = document.getElementById('ticketModal');';
echo 'window.onclick = function(event) {';
echo 'if (event.target == modal) {';
echo 'modal.style.display = "none";';
echo '}';
echo '}';
echo '</script>';
echo '';
echo '</body>';
echo '</html>';
?>
